version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: test
    commit-message:
      prefix: "chore(deps)"
      include: scope
    labels:
      - dependencies
      - go

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: test
    commit-message:
      prefix: "ci(deps)"
      include: scope
    labels:
      - dependencies
      - github-actions
