SHELL := /usr/bin/env bash

MODULE      := github.com/furkandedizkan/handy-tools
BIN_DIR     := bin
HANDY_BIN   := $(BIN_DIR)/handy
CLI_BIN     := $(BIN_DIR)/htools
SERVER_BIN  := $(BIN_DIR)/htoolsd
MCP_BIN     := $(BIN_DIR)/htools-mcp
GUI_BIN     := $(BIN_DIR)/htools-gui

GO          ?= go
GOFLAGS     ?=
LDFLAGS     ?= -s -w
PKGS        := ./...

# Derive version from git so every local build — `make build`, `make gui-build`,
# and `make gui` (which threads LDFLAGS into `go run`) — reports the most
# recent calver tag, matching what the release pipeline bakes in via
# .goreleaser.yaml. We use `--abbrev=0` so the label stays the clean tag
# (e.g. v2026.5.18-beta.1) instead of "v2026.5.18-beta.1-259-gac11649-dirty"
# when HEAD is past the tag or the tree is dirty. When git is unavailable
# (extracted tarball builds) VERSION is empty and the embedded fallback in
# internal/buildinfo/version.txt (0.0.0-dev) wins.
VERSION     ?= $(shell git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')
ifneq ($(VERSION),)
LDFLAGS     += -X $(MODULE)/internal/buildinfo.Version=$(VERSION)
endif

# The Wails desktop build needs three tags: `wails` (this repo's own — selects
# the real app over the CGO-free stub), `production` (Wails' own — without it
# the binary aborts at startup with "will not build without the correct build
# tags"), and `webkit2_41` on systems with only webkit2gtk-4.1 (Ubuntu 24.04+).
# The last is detected via pkg-config so one command builds on 4.0 and 4.1.
WAILS_TAGS  := wails production$(if $(shell pkg-config --exists webkit2gtk-4.1 2>/dev/null && echo y), webkit2_41,)

.DEFAULT_GOAL := help

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "} {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

.PHONY: build
build: web $(HANDY_BIN) $(CLI_BIN) $(SERVER_BIN) $(MCP_BIN) ## Build web assets + all CLI binaries (front-door, CLI, daemon, MCP server)

$(HANDY_BIN):
	@mkdir -p $(BIN_DIR)
	$(GO) build $(GOFLAGS) -ldflags '$(LDFLAGS)' -o $(HANDY_BIN) ./cmd/handy

$(CLI_BIN):
	@mkdir -p $(BIN_DIR)
	$(GO) build $(GOFLAGS) -ldflags '$(LDFLAGS)' -o $(CLI_BIN) ./cmd/htools

$(SERVER_BIN):
	@mkdir -p $(BIN_DIR)
	$(GO) build $(GOFLAGS) -ldflags '$(LDFLAGS)' -o $(SERVER_BIN) ./cmd/htoolsd

$(MCP_BIN):
	@mkdir -p $(BIN_DIR)
	$(GO) build $(GOFLAGS) -ldflags '$(LDFLAGS)' -o $(MCP_BIN) ./cmd/htools-mcp

.PHONY: web
web: ## Build the Svelte frontend into web/dist (embedded by htoolsd)
	cd web && npm ci && npm run build
	@# vite build empties dist/ — re-create the marker so the directory
	@# remains tracked in git for downstream `go build` without Node.
	@touch web/dist/.gitkeep

.PHONY: web-dev
web-dev: ## Run Vite dev server with HMR (point it at a running htoolsd)
	cd web && npm run dev

.PHONY: handy
handy: ## Print the handy front-door help
	$(GO) run ./cmd/handy --help

.PHONY: cli
cli: ## Print the CLI help
	$(GO) run ./cmd/htools --help

.PHONY: serve
serve: ## Run the gRPC server
	$(GO) run ./cmd/htoolsd

.PHONY: mcp
mcp: ## Run the MCP server on stdio (wire it into an MCP client manually)
	$(GO) run ./cmd/htools-mcp

.PHONY: mcp-build
mcp-build: $(MCP_BIN) ## Build the MCP server binary into bin/htools-mcp

.PHONY: gui
gui: web ## Build the web UI and run the Wails desktop app
	$(GO) run -tags '$(WAILS_TAGS)' -ldflags '$(LDFLAGS)' ./cmd/htools-gui

.PHONY: gui-build
gui-build: web ## Build the Wails desktop app into bin/htools-gui
	@mkdir -p $(BIN_DIR)
	$(GO) build $(GOFLAGS) -tags '$(WAILS_TAGS)' -ldflags '$(LDFLAGS)' -o $(GUI_BIN) ./cmd/htools-gui

.PHONY: test
test: ## Run unit tests
	$(GO) test -race -count=1 $(PKGS)

.PHONY: cover
cover: ## Run tests with coverage report
	$(GO) test -race -count=1 -coverprofile=coverage.out $(PKGS)
	$(GO) tool cover -html=coverage.out -o coverage.html

.PHONY: fuzz
fuzz: ## Run short fuzz pass over the config YAML decoder
	$(GO) test -run=^$$ -fuzz=FuzzDecodeYAML -fuzztime=20s ./internal/config

# Stress harness: runs the per-package benchmarks (bench target) and the
# CLI workload sweep against synthetic fixtures generated by cmd/stressgen
# (stress target). The two are separate because benches are cheap and run
# on CI; the CLI sweep generates ~3 GB on disk and takes longer.
STRESS_DIR    ?= /tmp/handy-stress
STRESS_BENCH  ?= ./internal/tools/...
STRESS_COUNT  ?= 5

.PHONY: bench
bench: ## Run Go benchmarks over internal/tools/* (set STRESS_BENCH/STRESS_COUNT to override)
	$(GO) test -run=^$$ -bench=. -benchmem -count=$(STRESS_COUNT) $(STRESS_BENCH)

.PHONY: stress
stress: $(CLI_BIN) $(MCP_BIN) ## Generate stress fixtures and run CLI workloads against them
	@mkdir -p $(STRESS_DIR)
	@$(GO) build -o $(BIN_DIR)/stressgen ./cmd/stressgen
	@scripts/stress.sh $(STRESS_DIR) $(BIN_DIR)

.PHONY: lint
lint: ## Run linters
	golangci-lint run
	@if command -v buf >/dev/null 2>&1; then buf lint; else echo "buf not installed, skipping proto lint"; fi

.PHONY: proto
proto: ## Regenerate protobuf bindings
	buf generate

.PHONY: tidy
tidy: ## go mod tidy
	$(GO) mod tidy

.PHONY: clean
clean: ## Remove build artifacts
	rm -rf $(BIN_DIR) dist coverage.out coverage.html
	rm -rf web/dist/assets web/dist/index.html
	@# Keep web/dist/.gitkeep (committed) and web/placeholder.html.
