package server

import (
	"context"

	"github.com/furkandedizkan/handy-tools/internal/tools"
	"github.com/furkandedizkan/handy-tools/internal/tools/image"
)

// ImageHandler adapts the image tool package to the gRPC ImageService.
//
// It is intentionally a plain Go struct that does not depend on the generated
// proto package — the wire-level binding lives in adapter_proto.go and is
// generated by `make proto`. Keeping it this way lets the rest of the server
// be unit-tested without any protobuf toolchain installed.
type ImageHandler struct {
	Opts Options
}

// ConvertParams is the wire-shape-agnostic input.
type ConvertParams struct {
	Source       string
	TargetFormat image.Format
	Quality      int
	MaxWidth     int
	MaxHeight    int
	OutputDir    string
	OutputFile   string
	Overwrite    bool
}

// Convert runs a single conversion and forwards progress events to the
// caller-supplied emit closure. The closure is what bridges to the streaming
// gRPC reply.
func (h *ImageHandler) Convert(ctx context.Context, p ConvertParams, emit func(tools.Progress) error) error {
	src, err := h.Opts.CheckPath(p.Source)
	if err != nil {
		return err
	}
	out := p.OutputFile
	if out == "" && p.OutputDir != "" {
		if v, err := h.Opts.CheckPath(p.OutputDir); err == nil {
			out = v
		} else {
			return err
		}
	}
	ch := image.Convert(ctx, image.ConvertRequest{
		Source:       src,
		TargetFormat: p.TargetFormat,
		Output:       out,
		Overwrite:    p.Overwrite,
		Opts: image.Options{
			Quality:   p.Quality,
			MaxWidth:  p.MaxWidth,
			MaxHeight: p.MaxHeight,
		},
	})
	for prog := range ch {
		if err := emit(prog); err != nil {
			return err
		}
	}
	return nil
}

// BatchConvertParams is the wire-shape-agnostic input for a batch job: every
// source is converted to the same TargetFormat and written into OutputDir.
//
// Parallelism is the worker-pool size for image.BatchConvert; 0 (the default)
// auto-sizes to runtime.GOMAXPROCS(0).
type BatchConvertParams struct {
	Sources      []string
	TargetFormat image.Format
	Quality      int
	MaxWidth     int
	MaxHeight    int
	OutputDir    string
	Overwrite    bool
	Parallelism  int
}

// BatchConvert converts every source in one job, forwarding the per-file and
// terminal progress events from image.BatchConvert to emit. Each source path
// and the output directory are run through CheckPath.
func (h *ImageHandler) BatchConvert(ctx context.Context, p BatchConvertParams, emit func(tools.Progress) error) error {
	srcs := make([]string, 0, len(p.Sources))
	for _, s := range p.Sources {
		v, err := h.Opts.CheckPath(s)
		if err != nil {
			return err
		}
		srcs = append(srcs, v)
	}
	out, err := h.Opts.CheckPath(p.OutputDir)
	if err != nil {
		return err
	}
	ch := image.BatchConvert(ctx, image.BatchConvertRequest{
		Sources:      srcs,
		TargetFormat: p.TargetFormat,
		Opts: image.Options{
			Quality:   p.Quality,
			MaxWidth:  p.MaxWidth,
			MaxHeight: p.MaxHeight,
		},
		OutputDir:   out,
		Overwrite:   p.Overwrite,
		Parallelism: p.Parallelism,
	})
	for prog := range ch {
		if err := emit(prog); err != nil {
			return err
		}
	}
	return nil
}
