package server

import (
	"context"

	"github.com/furkandedizkan/handy/internal/tools"
	"github.com/furkandedizkan/handy/internal/tools/image"
)

// ImageHandler adapts the image tool package to the gRPC ImageService.
//
// It is intentionally a plain Go struct that does not depend on the generated
// proto package — the wire-level binding lives in adapter_proto.go and is
// generated by `make proto`. Keeping it this way lets the rest of the server
// be unit-tested without any protobuf toolchain installed.
type ImageHandler struct {
	Opts Options
}

// ConvertParams is the wire-shape-agnostic input.
type ConvertParams struct {
	Source       string
	TargetFormat image.Format
	Quality      int
	MaxWidth     int
	MaxHeight    int
	OutputDir    string
	OutputFile   string
	Overwrite    bool
}

// Convert runs a single conversion and forwards progress events to the
// caller-supplied emit closure. The closure is what bridges to the streaming
// gRPC reply.
func (h *ImageHandler) Convert(ctx context.Context, p ConvertParams, emit func(tools.Progress) error) error {
	src, err := h.Opts.CheckPath(p.Source)
	if err != nil {
		return err
	}
	out := p.OutputFile
	if out == "" && p.OutputDir != "" {
		if v, err := h.Opts.CheckPath(p.OutputDir); err == nil {
			out = v
		} else {
			return err
		}
	}
	ch := image.Convert(ctx, image.ConvertRequest{
		Source:       src,
		TargetFormat: p.TargetFormat,
		Output:       out,
		Overwrite:    p.Overwrite,
		Opts: image.Options{
			Quality:   p.Quality,
			MaxWidth:  p.MaxWidth,
			MaxHeight: p.MaxHeight,
		},
	})
	for prog := range ch {
		if err := emit(prog); err != nil {
			return err
		}
	}
	return nil
}
