#!/usr/bin/env bash
# Stress harness — drives bin/htools against fixtures generated by
# bin/stressgen. Times each workload with /usr/bin/time -v and writes the
# raw output to $STRESS_DIR/log/<workload>.log.
#
# Invoked by `make stress`. The /usr/bin/time call is deliberately kept
# format-stable across systems with util-linux time present; macOS users
# get the BSD time fallback (different format, still useful).

set -uo pipefail

STRESS_DIR=${1:?usage: stress.sh <stress-dir> <bin-dir>}
BIN_DIR=${2:?usage: stress.sh <stress-dir> <bin-dir>}

STRESSGEN="$BIN_DIR/stressgen"
HTOOLS="$BIN_DIR/htools"
LOG_DIR="$STRESS_DIR/log"

mkdir -p "$LOG_DIR"

# Cross-platform wall+RSS reporter. GNU time -v is the richest; fall back
# to `time` builtin when GNU time is absent (macOS default).
TIME_BIN=$(command -v /usr/bin/time || true)

# run_timed <label> [allowed-exit] <cmd...>
# allowed-exit defaults to 0 — htools diff-tree returns 1 when trees differ,
# which is success for the stress harness, so we pass allowed-exit=1 there.
run_timed() {
    local label="$1"; shift
    local allowed=0
    if [[ "$1" =~ ^[0-9]+$ ]]; then
        allowed="$1"; shift
    fi
    local log="$LOG_DIR/$label.log"
    echo "=== $label" | tee "$log"
    local rc=0
    if [[ -n "$TIME_BIN" ]] && "$TIME_BIN" --version >/dev/null 2>&1; then
        "$TIME_BIN" -v "$@" >>"$log" 2>&1
        rc=$?
    else
        { time "$@"; } >>"$log" 2>&1
        rc=$?
    fi
    if [[ $rc -ne 0 && $rc -ne $allowed ]]; then
        echo "FAILED ($rc): $label (see $log)" >&2
        return 1
    fi
    grep -E 'Elapsed|Maximum resident|System time|User time' "$log" || true
}

generate() {
    local workload="$1"
    local dir="$STRESS_DIR/$workload"
    echo "+ stressgen --workload=$workload --dir=$dir"
    "$STRESSGEN" --workload="$workload" --dir="$dir"
}

# Hash workloads -------------------------------------------------------------
generate hash-set
run_timed hash-set-sha256 \
    "$HTOOLS" hash --algo sha256 --quiet "$STRESS_DIR/hash-set"/*.bin

generate hash-large
run_timed hash-large-sha256 \
    "$HTOOLS" hash --algo sha256 --quiet "$STRESS_DIR/hash-large/large_$((1<<30)).bin"

# Image workloads ------------------------------------------------------------
generate image-set
mkdir -p "$STRESS_DIR/image-set-out"
run_timed image-batch-convert-png \
    "$HTOOLS" convert --format png --out "$STRESS_DIR/image-set-out" --quiet --overwrite \
    "$STRESS_DIR/image-set"/*.jpg

# Archive workloads ----------------------------------------------------------
generate archive-tree
ARCHIVE_OUT="$STRESS_DIR/archive-tree.tar.gz"
run_timed archive-compress-tar-gz \
    "$HTOOLS" pack --format tar.gz --output "$ARCHIVE_OUT" --quiet "$STRESS_DIR/archive-tree"
mkdir -p "$STRESS_DIR/archive-tree-extracted"
run_timed archive-extract-tar-gz \
    "$HTOOLS" extract --out "$STRESS_DIR/archive-tree-extracted" --overwrite --quiet "$ARCHIVE_OUT"

# PDF workloads --------------------------------------------------------------
generate pdf-set
run_timed pdf-merge \
    "$HTOOLS" pdf merge --out "$STRESS_DIR/pdf-set-merged.pdf" --quiet \
    "$STRESS_DIR/pdf-set"/*.pdf
generate pdf-large
mkdir -p "$STRESS_DIR/pdf-large-split"
run_timed pdf-split-every-10 \
    "$HTOOLS" pdf split --every 10 --out "$STRESS_DIR/pdf-large-split" --quiet \
    "$STRESS_DIR/pdf-large/large_200p.pdf"

# Diff-tree workloads — exit 1 (trees differ) is expected. -------------------
generate difftrees-mtime
run_timed difftree-mtime 1 \
    "$HTOOLS" diff-tree --by mtime --quiet \
    "$STRESS_DIR/difftrees-mtime/A" "$STRESS_DIR/difftrees-mtime/B"
generate difftrees-hash
run_timed difftree-hash 1 \
    "$HTOOLS" diff-tree --by hash --quiet \
    "$STRESS_DIR/difftrees-hash/A" "$STRESS_DIR/difftrees-hash/B"

# Rename workload — operates on a directory, mutates it, so we work on a
# fresh copy so reruns of `make stress` stay idempotent.
generate rename-set
RENAME_SRC="$STRESS_DIR/rename-set-run"
rm -rf "$RENAME_SRC"
cp -a "$STRESS_DIR/rename-set" "$RENAME_SRC"
run_timed rename-numeric-prefix \
    "$HTOOLS" rename --pattern '^(\d+)$' --replace 'file_$1.txt' --quiet "$RENAME_SRC"

# Doctor smoke ---------------------------------------------------------------
run_timed doctor "$HTOOLS" doctor

echo
echo "Stress sweep complete. Per-workload logs in: $LOG_DIR"
